Repository bounswe/bounswe2022group4, pull requests merged in 2022-12, with the labels that each got.

#352 Backend: Token Authentication provided by Django REST framework implemented.
  .github/workflows/backend.yml
  backend/heka/heka/settings.py
  backend/heka/heka/urls.py
  backend/heka/users/apps.py
  backend/heka/users/models.py
  backend/heka/users/serializers.py
  backend/heka/users/tests.py
  backend/heka/users/views.py
Labels: Priority - Medium, Status: Review Needed, Language - Python, Team - Backend

#353 Backend: Token Authentication provided by Django REST framework implemented.
  backend/heka/heka/settings.py
  backend/heka/heka/urls.py
  backend/heka/users/apps.py
  backend/heka/users/models.py
  backend/heka/users/serializers.py
  backend/heka/users/tests.py
  backend/heka/users/views.py
Labels: Priority - Medium, Status: Review Needed, Language - Python, Team - Backend

#354 Frontend: Doctor Signup
  heka-front/package-lock.json
  heka-front/package.json
  heka-front/src/components/Header/Header.js
  heka-front/src/components/Tab/Tab.js
  heka-front/src/pages/ProfilePage/ProfilePage.js
  heka-front/src/pages/ProfilePage/profilePage.css
  heka-front/src/pages/SignInPage/SignInPage.css
  heka-front/src/pages/SignUpPage/SignUpPage.css
  heka-front/src/pages/SignUpPage/SignUpPage.js
Labels: Category - To Do, Priority - High, Status: Completed, Language - React.js, Team - Frontend

#356 Frontend: Username Privacy
  heka-front/src/App.js
  heka-front/src/components/PostBox/PostBox.js
  heka-front/src/pages/HomePage/HomePage.js
Labels: Category - To Do, Priority - High, Status: Completed, whom: individual, Difficulty - Medium, Language - React.js, Team - Frontend

#360 Frontend: Authentication Token
  heka-front/src/App.js
  heka-front/src/pages/SignInPage/SignInPage.js
  heka-front/src/pages/SignUpPage/SignUpPage.js
Labels: Category - To Do, Priority - High, Status: Completed, Difficulty - Medium, Language - React.js, Team - Frontend

#362 Frontend: Comment Functionality
  heka-front/src/components/Comment/Comment.js
  heka-front/src/components/CommentBox/CommentBox.js
  heka-front/src/components/CreateComment/CreateComment.js
  heka-front/src/components/Post/Post.js
  heka-front/src/components/PostBox/PostBox.js
  heka-front/src/pages/HomePage/HomePage.js
Labels: Category - To Do, Priority - High, whom: individual, Language - React.js, Team - Frontend

#366 Frontend: Annotations Structure
  heka-front/package-lock.json
  heka-front/package.json
  heka-front/src/components/CommentBox/CommentBox.js
  heka-front/src/components/Post/Post.js
Labels: Category - To Do, Priority - High, whom: individual, Difficulty - Hard, Language - React.js, Team - Frontend

#369 Backend: Implementation of create, update, delete, and fetch of comments completed.
  backend/heka/posts/models.py
  backend/heka/posts/serializers.py
  backend/heka/posts/urls.py
  backend/heka/posts/views.py
Labels: Priority - Medium, Status: Review Needed, Language - Python, Team - Backend

#373 Heka backend profilepage
  backend/heka/docker-compose.yml
  backend/heka/users/models.py
  backend/heka/users/serializers.py
  backend/heka/users/urls.py
  backend/heka/users/views.py
Labels: Category - Enhancement, Status: Completed, Priority: Severe, Difficulty - Hard, Backend, Team - Backend

#377 Backend: Implements some functionalities and handles inconsistencies.
  backend/heka/posts/models.py
  backend/heka/posts/urls.py
  backend/heka/posts/views.py
  backend/heka/users/views.py
Labels: Priority - Medium, Status: Review Needed, Language - Python, Team - Backend

#383 Backend: Fixes the permission requirements for update and delete functionalities of Post and Comment models.
  backend/heka/posts/permissions.py
  backend/heka/posts/views.py
Labels: Status: Review Needed, Language - Python, Team - Backend

#384 Frontend: Category Section
  heka-front/package-lock.json
  heka-front/src/components/SideBar/SideBar.css
  heka-front/src/components/SideBar/SideBar.js
  heka-front/src/pages/HomePage/HomePage.css
  heka-front/src/pages/HomePage/HomePage.js
Labels: Priority - Medium, Status: Review Needed, Frontend

#392 Frontend: Forgot Password
  heka-front/src/App.js
  heka-front/src/components/SideBar/SideBar.css
  heka-front/src/components/SideBar/SideBar.js
  heka-front/src/pages/ForgotPassword/ForgotPassword.css
  heka-front/src/pages/ForgotPassword/ForgotPassword.js
  heka-front/src/pages/HomePage/HomePage.css
  heka-front/src/pages/SignInPage/SignInPage.js
Labels: Priority - Medium, Status: Review Needed, Frontend

#401 Backend: Modifies response bodies of APIs handling listing and updating of posts and comments.
  backend/heka/posts/models.py
  backend/heka/posts/serializers.py
  backend/heka/posts/views.py
Labels: Priority - Medium, Status: Review Needed, Language - Python, Team - Backend

#388 Frontend: Post Structure Backend Connection
  heka-front/src/App.js
  heka-front/src/api/ApiInstance.js
  heka-front/src/api/Backend/Backend.js
  heka-front/src/components/CreatePost/CreatePost.js
  heka-front/src/components/Post/Post.js
  heka-front/src/components/PostBox/PostBox.js
  heka-front/src/pages/HomePage/HomePage.js
  heka-front/src/pages/SignInPage/SignInPage.js
  heka-front/src/pages/SignUpPage/SignUpPage.js
Labels: Category - To Do, Priority - High, Status: Completed, Difficulty - Hard, Language - React.js, Team - Frontend

#402 Backend: Handles some inconsistencies related to last update time of posts and comments.
  backend/heka/posts/models.py
  backend/heka/posts/serializers.py
  backend/heka/posts/views.py
Labels: Priority - Medium, Status: Review Needed, Language - Python, Team - Backend

#405 Frontend: Comment Backend Connection
  heka-front/src/api/Backend/Backend.js
  heka-front/src/components/Comment/Comment.js
  heka-front/src/components/CommentBox/CommentBox.js
  heka-front/src/components/CreateComment/CreateComment.js
  heka-front/src/components/Post/Post.js
Labels: Priority - High, Status: Completed, whom: individual, Difficulty - Hard, Language - React.js, Team - Frontend

#406 Heka backend forget password
  backend/heka/chat/views.py
  backend/heka/heka/settings.py
  backend/heka/users/models.py
  backend/heka/users/urls.py
  backend/heka/users/views.py
Labels: Priority - High

#409 Front: Verification of Email UI Improvement
  heka-front/src/pages/ForgotPassword/ForgotPassword.css
  heka-front/src/pages/ForgotPassword/ForgotPassword.js
Labels: Priority - High, Status: Review Needed, Language - React.js, Frontend

#411 Frontend: Backend Connection For Vote Post
  heka-front/src/api/Backend/Backend.js
  heka-front/src/components/CommentBox/CommentBox.js
  heka-front/src/components/Post/Post.js
Labels: Category - To Do, Priority - High, whom: individual, Difficulty - Hard, Language - React.js, Team - Frontend

#414 Frontend Bug: Doctor Sign-Up Button Size Exceeds Form Container
  heka-front/src/components/SideBar/SideBar.css
  heka-front/src/components/SideBar/SideBar.js
  heka-front/src/pages/SignUpPage/SignUpPage.css
  heka-front/src/pages/SignUpPage/SignUpPage.js
Labels: Category - Bug, Priority - High, Status: Review Needed, Language - React.js

#416 Frontend: Backend Connection for Forget Password and Error Messages
  heka-front/src/api/Backend/Backend.js
  heka-front/src/pages/ForgotPassword/ForgotPassword.css
  heka-front/src/pages/ForgotPassword/ForgotPassword.js
Labels: Status: Review Needed, Language - React.js, Frontend

#424 Backend: Fixes tiny bugs.
  backend/heka/posts/views.py
Labels: Priority - High, Status: Review Needed, Team - Backend

#429 Frontend: Loading States
  heka-front/package-lock.json
  heka-front/package.json
  heka-front/src/components/CommentBox/CommentBox.js
  heka-front/src/components/CreatePost/CreatePost.js
  heka-front/src/components/PostBox/PostBox.js
  heka-front/src/components/SearchBar/SearchBar.css
  heka-front/src/components/SearchBar/SearchBar.js
  heka-front/src/pages/HomePage/HomePage.js
Labels: Priority - High, Status: Completed, whom: individual, Difficulty - Hard, Language - React.js, Team - Frontend

#435 Backend: profilepage tests
  backend/heka/users/tests.py
  backend/heka/users/views.py
Labels: Priority - High, Status: Review Needed, Difficulty - Hard, Team - Backend

#438 Backend: Implements fetch comment.
  backend/heka/posts/urls.py
  backend/heka/posts/views.py
Labels: Priority - High, Status: Review Needed, Team - Backend

#474 Mobile: Junit base and Email and Username validator tests
  heka-mobile/app/build.gradle
  heka-mobile/app/src/main/java/com/bounswe/heka/utils/EmailValidator.kt
  heka-mobile/app/src/test/java/com/bounswe/heka/EmailValidatorUnitTest.kt
  heka-mobile/app/src/test/java/com/bounswe/heka/UsernameValidatorUnitTest.kt
Labels: Mobile

#487 Frontend: Unit Tests for Posts
  heka-front/package-lock.json
  heka-front/src/components/Post/Post.js
  heka-front/src/tests/Post.test.js
  heka-front/src/tests/PostBox.test.js
Labels: Category - To Do, Priority - High, Status: Completed, whom: individual, Difficulty - Hard, Language - React.js, Team - Frontend

#492 Executive Summary Part filled
  deliverables/CMPE451_Customer_Presentation_Milestone_2/Customer_Milestone_2.md
Labels: Category - Documentation, Priority: Severe, whom: team, Difficulty - Hard

#502 Dark theme problem fixed
  heka-mobile/app/src/main/res/values-night/themes.xml
  heka-mobile/app/src/main/res/values/themes.xml
Labels: Category - Bug, Mobile

#507 Frontend: Single Post Page and URL
  heka-front/src/App.js
  heka-front/src/api/Backend/Backend.js
  heka-front/src/components/Post/Post.js
  heka-front/src/components/PostBox/PostBox.js
  heka-front/src/pages/HomePage/HomePage.js
  heka-front/src/pages/PostPage/PostPage.css
  heka-front/src/pages/PostPage/PostPage.js
Labels: Priority - High, Status: Completed, whom: individual, Difficulty - Medium, Language - React.js, Team - Frontend

#528 Backend: Search Application - Initialized the application and added the user search functionality
  backend/heka/heka/settings.py
  backend/heka/heka/urls.py
  backend/heka/search/__init__.py
  backend/heka/search/admin.py
  backend/heka/search/apps.py
  backend/heka/search/migrations/__init__.py
  backend/heka/search/models.py
  backend/heka/search/tests.py
  backend/heka/search/views.py
  backend/heka/textSearch/__init__.py
  backend/heka/textSearch/admin.py
  backend/heka/textSearch/apps.py
  backend/heka/textSearch/migrations/__init__.py
  backend/heka/textSearch/models.py
  backend/heka/textSearch/tests.py
  backend/heka/textSearch/urls.py
  backend/heka/textSearch/views.py
Labels: Category - Help Wanted, Status: Revision Needed, Difficulty - Medium, Language - Python, Team - Backend

#512 Frontend: Text Annotation Structure
  heka-front/package-lock.json
  heka-front/package.json
  heka-front/src/App.js
  heka-front/src/components/Post/Post.js
  heka-front/src/components/TextAnnotation/TextAnnotation.js
Labels: Priority - High, Status: Completed, whom: individual, Difficulty - Hard, Language - React.js, Team - Frontend

#537 Backend: Annotations endpoints and database
  backend/heka/annotations/__init__.py
  backend/heka/annotations/admin.py
  backend/heka/annotations/apps.py
  backend/heka/annotations/migrations/__init__.py
  backend/heka/annotations/models.py
  backend/heka/annotations/serializers.py
  backend/heka/annotations/tests.py
  backend/heka/annotations/urls.py
  backend/heka/annotations/views.py
  backend/heka/docker-compose.yml
  backend/heka/heka/settings.py
  backend/heka/heka/urls.py
  backend/heka/routers/AnnoRouter.py
Labels: Priority - High, Status: In Progress, Difficulty - Hard, Backend

#534 Backend: Search Application - Added the post search functionality
  backend/heka/docker-compose.yml
  backend/heka/textSearch/urls.py
  backend/heka/textSearch/views.py
Labels: Category - Help Wanted, Status: Completed, Status: Review Needed, Difficulty - Medium, Language - Python, Team - Backend

#539 Backend: Adds annotations to the heka-backend
  backend/heka/annotations/__init__.py
  backend/heka/annotations/admin.py
  backend/heka/annotations/apps.py
  backend/heka/annotations/migrations/__init__.py
  backend/heka/annotations/models.py
  backend/heka/annotations/serializers.py
  backend/heka/annotations/tests.py
  backend/heka/annotations/urls.py
  backend/heka/annotations/views.py
  backend/heka/docker-compose.yml
  backend/heka/heka/settings.py
  backend/heka/heka/urls.py
  backend/heka/routers/AnnoRouter.py
Labels: Priority - High, Status: Review Needed, Difficulty - Hard, Backend, Team - Backend

#541 Frontend: Email Verification for Sign Up
  heka-front/package-lock.json
  heka-front/package.json
  heka-front/src/App.js
  heka-front/src/pages/SignUpPage/SignUpPage.js
  heka-front/src/pages/SignUpVerificationPage/SignUpVerificationPage.css
  heka-front/src/pages/SignUpVerificationPage/SignUpVerificationPage.js
  heka-front/src/tests/ForgotPassword.test.js
Labels: Status: Completed, Language - React.js, Frontend

#543 Backend: Search Application - Bug fix about count parameter
  backend/heka/textSearch/views.py
Labels: Category - Bug, Priority - Medium, Status: Review Needed, Team - Backend

#532 Frontend: Single Profile Page with Dynamic URL
  heka-front/src/App.js
  heka-front/src/components/Navbar/Navbar.js
  heka-front/src/components/Post/Post.js
  heka-front/src/pages/ProfilePage/ProfilePage.js
Labels: Priority - High, whom: individual, Difficulty - Hard, Language - React.js, Team - Frontend

#546 Backend: Change permission for the image annotation endpoints
  backend/heka/annotations/views.py
Labels: Category - Bug, Priority - Medium, Status: In Progress, Difficulty - Easy, Backend, Team - Backend

#549 Frontend Bug: Failure of the Compilation and Test Deployment
  heka-front/src/components/Navbar/Navbar.js
Labels: Category - Bug, Priority - High, Status: Completed, Language - React.js

#557 Frontend: Image Annotation Backend Connection
  heka-front/src/api/Backend/Backend.js
  heka-front/src/components/Post/Post.js
Labels: Priority - High, whom: individual, Difficulty - Hard, Language - React.js, Team - Frontend

#561 Frontend Bug: Search Results Container Remove Search Bar
  heka-front/src/components/Navbar/Navbar.js
  heka-front/src/components/SearchBar/SearchBar.css
  heka-front/src/pages/SignUpPage/SignUpPage.js
Labels: Category - Bug, Status: Completed, whom: individual, Frontend

#563 Backend: Search Functionality - Update response format
  backend/heka/textSearch/views.py
Labels: Category - Help Wanted, Priority - High, Status: Completed, Status: Review Needed

#568 Frontend: Text Annotation Backend Connection
  heka-front/src/App.js
  heka-front/src/api/Backend/Backend.js
  heka-front/src/components/Navbar/Navbar.js
  heka-front/src/components/Post/Post.js
  heka-front/src/components/PostBox/PostBox.js
  heka-front/src/components/TextAnnotation/TextAnnotation.js
Labels: Priority - High, Status: Completed, whom: individual, Difficulty - Hard, Language - React.js, Team - Frontend

#574 Frontend : Search Functioanlity for Posts
  heka-front/src/api/Backend/Backend.js
  heka-front/src/components/SearchBar/SearchBar.js
Labels: Status: Completed, whom: individual, Language - React.js, Frontend

#588 Frontend: Sign Up Password Confirmation for Regular Users
  heka-front/src/pages/SignUpPage/SignUpPage.js
Labels: Status: Completed, whom: individual, Language - React.js, Frontend

#592 Frontend: Local Storage For Authentication Token and User Info
  heka-front/src/App.js
  heka-front/src/components/Chat/MessageChat.js
  heka-front/src/components/Comment/Comment.js
  heka-front/src/components/CommentBox/CommentBox.js
  heka-front/src/components/Navbar/Navbar.js
  heka-front/src/components/Post/Post.js
  heka-front/src/components/PostBox/PostBox.js
  heka-front/src/pages/EditProfilePage/EditProfilePage.js
  heka-front/src/pages/HomePage/HomePage.js
  heka-front/src/pages/PostPage/PostPage.js
  heka-front/src/pages/ProfilePage/ProfilePage.js
  heka-front/src/pages/SignInPage/SignInPage.js
Labels: Category - To Do, Priority - High, Status: Completed, whom: individual, Difficulty - Hard, Language - React.js, Team - Frontend

#594 Frontend: Profile Page Unit Test Cases
  heka-front/src/pages/ProfilePage/ProfilePage.js
  heka-front/src/tests/ProfilePage.test.js
Labels: Priority - High, Status: Completed, whom: individual, Difficulty - Hard, Language - React.js, Team - Frontend

#597 Frontend : Search Functioanlity for Users
  heka-front/src/api/Backend/Backend.js
  heka-front/src/components/SearchBar/SearchBar.js
Labels: Status: Review Needed, whom: individual, Language - React.js, Frontend

#601 Frontend: Unit Test for Search Functionality
  heka-front/package-lock.json
  heka-front/package.json
  heka-front/src/tests/ForgotPassword.test.js
  heka-front/src/tests/SearchBar.test.js
Labels: Status: In Test, whom: individual, Language - React.js, Frontend

#565 Backend: Search Application - Bug fix about sort functionality
  backend/heka/textSearch/views.py
Labels: Category - Bug, Priority - High, Status: Completed, Status: Review Needed

#603 Frontend: Comment Number Display
  heka-front/package-lock.json
  heka-front/src/components/Comment/Comment.js
  heka-front/src/components/CommentBox/CommentBox.js
  heka-front/src/components/Post/Post.js
  heka-front/src/components/PostBox/PostBox.js
  heka-front/src/pages/SignUpPage/SignUpPage.js
Labels: Category - Enhancement, Priority - Medium, Status: Review Needed, whom: individual, Language - React.js, Team - Frontend

#602 Frontend: Password check functionality is added
  heka-front/package-lock.json
  heka-front/src/pages/SignUpPage/SignUpPage.js
Labels: Priority - Medium, Status: Review Needed, Language - React.js, Team - Frontend

#609 Frontend: Sign Up Verification Backend Connection
  heka-front/src/pages/SignUpPage/SignUpPage.js
  heka-front/src/pages/SignUpVerificationPage/SignUpVerificationPage.js
Labels: Status: Completed, whom: individual, Language - React.js, Frontend

#612 Frontend: Logo Implementation
  heka-front/public/favicon.ico
  heka-front/public/logoX/0.75x/Varlık 1ldpi.png
  heka-front/public/logoX/1.5x/Varlık 1hdpi.png
  heka-front/public/logoX/1x/Varlık 1mdpi.png
  heka-front/public/logoX/2x/Varlık 1xhdpi.png
  heka-front/public/logoX/3x/Varlık 1xxhdpi.png
  heka-front/public/logoX/4x/Varlık 1xxxhdpi.png
  heka-front/src/components/Navbar/Navbar.js
  heka-front/src/components/Navbar/logo.svg
Labels: Priority - High, Status: Completed, whom: individual, Difficulty - Medium, Language - React.js, Team - Frontend

#617 Frontend: Unit Tests for Sign Up Verification
  heka-front/src/tests/SignUpVerification.test.js
Labels: Status: In Test, whom: individual, Language - React.js, Frontend

#615 Adding button for sending message to other users
  heka-front/src/components/Chat/MessageChat.js
  heka-front/src/pages/ProfilePage/ProfilePage.js
Labels: Frontend

#610 Backend: Unit Tests for annotations
  backend/heka/annotations/tests.py
  backend/heka/annotations/views.py
  backend/heka/docker-compose.test.yml
  backend/heka/users/serializers.py
  backend/heka/users/tests.py
Labels: Category - Enhancement, Priority - Medium, Status: Review Needed, Difficulty - Medium, Language - Python, Backend, Team - Backend

#604 Backend: Implements unit test for creation of posts.
  backend/heka/posts/tests.py
Labels: Status: Review Needed, Team - Backend

#619 Backend: Implements unit tests for update and delete post.
  backend/heka/posts/tests.py
Labels: Status: Review Needed, Team - Backend

#622 Frontend: ChatBot Implementation
  heka-front/package-lock.json
  heka-front/package.json
  heka-front/src/App.js
  heka-front/src/components/ChatBot/ChatBot.js
  heka-front/src/components/Navbar/Navbar.js
  heka-front/src/pages/ChatBotPage/ChatBotPage.js
Labels: Category - To Do, Priority - High, Status: Completed, whom: individual, Difficulty - Hard, Language - React.js, Team - Frontend

#623 Frontend: Comment highlights are added and post shadow is added
  heka-front/src/components/Comment/Comment.js
  heka-front/src/components/Post/Post.js
Labels: Category - Enhancement, Status: Completed, Difficulty - Easy, Language - React.js, Team - Frontend

#625 Frontend: Comment Orders are Added.
  heka-front/src/components/CommentBox/CommentBox.js
Labels: Category - Enhancement, Priority - High, Status: Completed, Language - React.js, Team - Frontend

#631 Frontend Bug: Sign Up Verification Code
  heka-front/src/pages/SignUpVerificationPage/SignUpVerificationPage.js
Labels: Category - Bug, Priority - High, Language - React.js, Frontend

#628 Frontend: Added Unit Tests for CommentBox and Comment Components
  heka-front/src/tests/Comment.test.js
  heka-front/src/tests/CommentBox.test.js
Labels: Priority - Medium, Language - React.js, Team - Frontend
