Repository bounswe/bounswe2022group4, pull requests merged in 2022-05, with the labels that each got.

#123 Feature/home page
  practice_app/main_app/main_app/.idea/.gitignore
  practice_app/main_app/main_app/.idea/inspectionProfiles/profiles_settings.xml
  practice_app/main_app/main_app/.idea/main_app.iml
  practice_app/main_app/main_app/.idea/misc.xml
  practice_app/main_app/main_app/.idea/modules.xml
  practice_app/main_app/main_app/.idea/vcs.xml
  practice_app/main_app/main_app/db.sqlite3
  practice_app/main_app/main_app/main_app/__init__.py
  practice_app/main_app/main_app/main_app/__pycache__/__init__.cpython-39.pyc
  practice_app/main_app/main_app/main_app/__pycache__/settings.cpython-39.pyc
  practice_app/main_app/main_app/main_app/__pycache__/urls.cpython-39.pyc
  practice_app/main_app/main_app/main_app/__pycache__/wsgi.cpython-39.pyc
  practice_app/main_app/main_app/main_app/asgi.py
  practice_app/main_app/main_app/main_app/settings.py
  practice_app/main_app/main_app/main_app/urls.py
  practice_app/main_app/main_app/main_app/wsgi.py
  practice_app/main_app/main_app/manage.py
  practice_app/main_app/main_app/post/__init__.py
  practice_app/main_app/main_app/post/__pycache__/__init__.cpython-39.pyc
  practice_app/main_app/main_app/post/__pycache__/admin.cpython-39.pyc
  practice_app/main_app/main_app/post/__pycache__/apps.cpython-39.pyc
  practice_app/main_app/main_app/post/__pycache__/models.cpython-39.pyc
  practice_app/main_app/main_app/post/__pycache__/urls.cpython-39.pyc
  practice_app/main_app/main_app/post/__pycache__/views.cpython-39.pyc
  practice_app/main_app/main_app/post/admin.py
  practice_app/main_app/main_app/post/apps.py
  practice_app/main_app/main_app/post/migrations/__init__.py
  practice_app/main_app/main_app/post/migrations/__pycache__/__init__.cpython-39.pyc
  practice_app/main_app/main_app/post/models.py
  practice_app/main_app/main_app/post/static/post/main.css
  practice_app/main_app/main_app/post/templates/post/base.html
  practice_app/main_app/main_app/post/templates/post/home.html
  practice_app/main_app/main_app/post/tests.py
  practice_app/main_app/main_app/post/urls.py
  practice_app/main_app/main_app/post/views.py
Labels: Priority - High

#126 Feature registration
  practice_app/main_app/.idea/misc.xml
  practice_app/main_app/db.sqlite3
  practice_app/main_app/main_app/__pycache__/__init__.cpython-39.pyc
  practice_app/main_app/main_app/__pycache__/settings.cpython-39.pyc
  practice_app/main_app/main_app/__pycache__/urls.cpython-39.pyc
  practice_app/main_app/main_app/__pycache__/wsgi.cpython-39.pyc
  practice_app/main_app/main_app/settings.py
  practice_app/main_app/main_app/urls.py
  practice_app/main_app/post/__pycache__/__init__.cpython-39.pyc
  practice_app/main_app/post/__pycache__/admin.cpython-39.pyc
  practice_app/main_app/post/__pycache__/apps.cpython-39.pyc
  practice_app/main_app/post/__pycache__/models.cpython-39.pyc
  practice_app/main_app/post/__pycache__/urls.cpython-39.pyc
  practice_app/main_app/post/__pycache__/views.cpython-39.pyc
  practice_app/main_app/post/migrations/__pycache__/0001_initial.cpython-39.pyc
  practice_app/main_app/post/migrations/__pycache__/__init__.cpython-39.pyc
  practice_app/main_app/post/templates/post/base.html
  practice_app/main_app/users/__init__.py
  practice_app/main_app/users/__pycache__/__init__.cpython-39.pyc
  practice_app/main_app/users/__pycache__/admin.cpython-39.pyc
  practice_app/main_app/users/__pycache__/apps.cpython-39.pyc
  practice_app/main_app/users/__pycache__/models.cpython-39.pyc
  practice_app/main_app/users/__pycache__/views.cpython-39.pyc
  practice_app/main_app/users/admin.py
  practice_app/main_app/users/apps.py
  practice_app/main_app/users/migrations/__init__.py
  practice_app/main_app/users/migrations/__pycache__/__init__.cpython-39.pyc
  practice_app/main_app/users/models.py
  practice_app/main_app/users/templates/users/register.html
  practice_app/main_app/users/tests.py
  practice_app/main_app/users/views.py
Labels: Priority - High, Status: Review Needed

#129 Feature/registrationapi
  practice_app/main_app/db.sqlite3
  practice_app/main_app/main_app/__pycache__/__init__.cpython-39.pyc
  practice_app/main_app/main_app/__pycache__/settings.cpython-39.pyc
  practice_app/main_app/main_app/__pycache__/urls.cpython-39.pyc
  practice_app/main_app/main_app/__pycache__/wsgi.cpython-39.pyc
  practice_app/main_app/main_app/urls.py
  practice_app/main_app/post/__pycache__/__init__.cpython-39.pyc
  practice_app/main_app/post/__pycache__/admin.cpython-39.pyc
  practice_app/main_app/post/__pycache__/apps.cpython-39.pyc
  practice_app/main_app/post/__pycache__/models.cpython-39.pyc
  practice_app/main_app/post/__pycache__/urls.cpython-39.pyc
  practice_app/main_app/post/__pycache__/views.cpython-39.pyc
  practice_app/main_app/post/migrations/__pycache__/0001_initial.cpython-39.pyc
  practice_app/main_app/post/migrations/__pycache__/__init__.cpython-39.pyc
  practice_app/main_app/users/__pycache__/__init__.cpython-39.pyc
  practice_app/main_app/users/__pycache__/admin.cpython-39.pyc
  practice_app/main_app/users/__pycache__/apps.cpython-39.pyc
  practice_app/main_app/users/__pycache__/models.cpython-39.pyc
  practice_app/main_app/users/__pycache__/serializers.cpython-39.pyc
  practice_app/main_app/users/__pycache__/views.cpython-39.pyc
  practice_app/main_app/users/migrations/__pycache__/__init__.cpython-39.pyc
  practice_app/main_app/users/serializers.py
  practice_app/main_app/users/templates/users/ListAllUsers.html
  practice_app/main_app/users/views.py
Labels: Priority - High, Status: Review Needed

#130 Delete post functionality is added
  practice_app/main_app/.gitignore
  practice_app/main_app/main_app/__pycache__/__init__.cpython-39.pyc
  practice_app/main_app/main_app/__pycache__/settings.cpython-39.pyc
  practice_app/main_app/main_app/__pycache__/urls.cpython-39.pyc
  practice_app/main_app/main_app/__pycache__/wsgi.cpython-39.pyc
  practice_app/main_app/post/__pycache__/__init__.cpython-39.pyc
  practice_app/main_app/post/__pycache__/admin.cpython-39.pyc
  practice_app/main_app/post/__pycache__/apps.cpython-39.pyc
  practice_app/main_app/post/__pycache__/models.cpython-39.pyc
  practice_app/main_app/post/__pycache__/urls.cpython-39.pyc
  practice_app/main_app/post/__pycache__/views.cpython-39.pyc
  practice_app/main_app/post/migrations/__pycache__/0001_initial.cpython-39.pyc
  practice_app/main_app/post/migrations/__pycache__/0002_post_location.cpython-39.pyc
  practice_app/main_app/post/migrations/__pycache__/__init__.cpython-39.pyc
  practice_app/main_app/post/models.py
  practice_app/main_app/post/templates/post/home.html
  practice_app/main_app/post/templates/post/post_confirm_delete.html
  practice_app/main_app/post/templates/post/post_detail.html
  practice_app/main_app/post/urls.py
  practice_app/main_app/post/views.py
  practice_app/main_app/users/__pycache__/__init__.cpython-39.pyc
  practice_app/main_app/users/__pycache__/admin.cpython-39.pyc
  practice_app/main_app/users/__pycache__/apps.cpython-39.pyc
  practice_app/main_app/users/__pycache__/models.cpython-39.pyc
  practice_app/main_app/users/__pycache__/serializers.cpython-39.pyc
  practice_app/main_app/users/__pycache__/views.cpython-39.pyc
  practice_app/main_app/users/migrations/__pycache__/__init__.cpython-39.pyc
Labels: Priority - High, Status: Review Needed

#145 API is implemented for registration with GET and POST. #124
  practice_app/main_app/db.sqlite3
  practice_app/main_app/main_app/settings.py
  practice_app/main_app/main_app/urls.py
  practice_app/main_app/users/views.py
Labels: Priority - High, Status: Review Needed

#149 like functionality implemented
  practice_app/main_app/post/models.py
  practice_app/main_app/post/templates/post/home.html
  practice_app/main_app/post/templates/post/post_detail.html
  practice_app/main_app/post/templates/post/user_posts.html
  practice_app/main_app/post/urls.py
  practice_app/main_app/post/views.py
Labels: Priority - Medium, Status: Review Needed

#151 like api implemented
  practice_app/main_app/post/templates/post/home.html
  practice_app/main_app/post/urls.py
  practice_app/main_app/post/views.py
Labels: Priority - High, Status: Review Needed

#148 comment system implemented
  practice_app/main_app/post/admin.py
  practice_app/main_app/post/models.py
  practice_app/main_app/post/templates/post/comment_form.html
  practice_app/main_app/post/templates/post/home.html
  practice_app/main_app/post/templates/post/post_detail.html
  practice_app/main_app/post/templates/post/user_posts.html
  practice_app/main_app/post/urls.py
  practice_app/main_app/post/views.py
Labels: Category - To Do, Priority - High, Difficulty - Hard, Language - Python, Language - HTML, Language - CSS

#154 Weather api for given city is added to sidebar
  practice_app/main_app/db.sqlite3
  practice_app/main_app/main_app/urls.py
  practice_app/main_app/post/migrations/__pycache__/0001_initial.cpython-39.pyc
  practice_app/main_app/post/migrations/__pycache__/0002_post_location.cpython-39.pyc
  practice_app/main_app/post/migrations/__pycache__/__init__.cpython-39.pyc
  practice_app/main_app/post/templates/post/base.html
  practice_app/main_app/users/migrations/__pycache__/__init__.cpython-39.pyc
  practice_app/main_app/users/models.py
  practice_app/main_app/users/templates/users/city_data.html
  practice_app/main_app/users/templates/users/city_form.html
  practice_app/main_app/users/views.py
Labels: Status: Review Needed

#155 User registration with same email problem is resolved #152
  practice_app/main_app/db.sqlite3
  practice_app/main_app/users/views.py
Labels: Category - Bug, Priority - High, Status: Review Needed

#165 Joke API and Delete Comment Features Implemented
  practice_app/umut_PS.txt
Labels: Category - To Do, Category - Documentation, Priority - High, Status: Completed, Status: Review Needed, Status: In Test, whom: team, Difficulty - Medium, Language - Python

#169 Testing registration
  practice_app/main_app/db.sqlite3
  practice_app/main_app/users/tests.py
  practice_app/main_app/users/tests/__init__.py
  practice_app/main_app/users/tests/__pycache__/__init__.cpython-39.pyc
  practice_app/main_app/users/tests/__pycache__/test_models.cpython-39.pyc
  practice_app/main_app/users/tests/__pycache__/test_urls.cpython-39.pyc
  practice_app/main_app/users/tests/__pycache__/test_views.cpython-39.pyc
  practice_app/main_app/users/tests/test_models.py
  practice_app/main_app/users/tests/test_urls.py
  practice_app/main_app/users/tests/test_views.py
Labels: Priority - Medium, Status: Review Needed

#178 JokeAPI and Delete Functionality in Comments are added
  practice_app/main_app/main_app/urls.py
  practice_app/main_app/post/migrations/0005_comment.py
  practice_app/main_app/post/migrations/__pycache__/0001_initial.cpython-310.pyc
  practice_app/main_app/post/migrations/__pycache__/0002_post_location.cpython-310.pyc
  practice_app/main_app/post/migrations/__pycache__/0003_post_likes.cpython-310.pyc
  practice_app/main_app/post/migrations/__pycache__/0004_post_dislikes.cpython-310.pyc
  practice_app/main_app/post/migrations/__pycache__/0005_comment.cpython-310.pyc
  practice_app/main_app/post/migrations/__pycache__/__init__.cpython-310.pyc
  practice_app/main_app/post/templates/post/base.html
  practice_app/main_app/post/templates/post/comment_confirm_delete.html
  practice_app/main_app/post/templates/post/display_jokes.html
  practice_app/main_app/post/templates/post/home.html
  practice_app/main_app/post/urls.py
  practice_app/main_app/post/views.py
  practice_app/main_app/users/migrations/0001_initial.py
  practice_app/main_app/users/migrations/__pycache__/0001_initial.cpython-310.pyc
  practice_app/main_app/users/migrations/__pycache__/__init__.cpython-310.pyc
  practice_app/main_app/users/views.py
Labels: Category - Bug

#193 Category API Implementation and Frontend - API connection
  practice_app/main_app/dnsApi/__pycache__/__init__.cpython-310.pyc
  practice_app/main_app/dnsApi/__pycache__/admin.cpython-310.pyc
  practice_app/main_app/dnsApi/__pycache__/apps.cpython-310.pyc
  practice_app/main_app/dnsApi/__pycache__/forms.cpython-310.pyc
  practice_app/main_app/dnsApi/__pycache__/models.cpython-310.pyc
  practice_app/main_app/dnsApi/__pycache__/urls.cpython-310.pyc
  practice_app/main_app/dnsApi/__pycache__/views.cpython-310.pyc
  practice_app/main_app/dnsApi/migrations/__pycache__/__init__.cpython-310.pyc
  practice_app/main_app/main_app/settings.py
  practice_app/main_app/post/admin.py
  practice_app/main_app/post/migrations/0006_post_category.py
  practice_app/main_app/post/migrations/0007_category.py
  practice_app/main_app/post/migrations/0008_alter_category_post.py
  practice_app/main_app/post/migrations/__pycache__/0001_initial.cpython-310.pyc
  practice_app/main_app/post/migrations/__pycache__/0002_post_location.cpython-310.pyc
  practice_app/main_app/post/migrations/__pycache__/0003_post_likes.cpython-310.pyc
  practice_app/main_app/post/migrations/__pycache__/0004_post_dislikes.cpython-310.pyc
  practice_app/main_app/post/migrations/__pycache__/0005_comment.cpython-310.pyc
  practice_app/main_app/post/migrations/__pycache__/0006_post_category.cpython-310.pyc
  practice_app/main_app/post/migrations/__pycache__/0007_category.cpython-310.pyc
  practice_app/main_app/post/migrations/__pycache__/0008_alter_category_post.cpython-310.pyc
  practice_app/main_app/post/migrations/__pycache__/__init__.cpython-310.pyc
  practice_app/main_app/post/models.py
  practice_app/main_app/post/serializers.py
  practice_app/main_app/post/templates/post/all_categories.html
  practice_app/main_app/post/templates/post/base.html
  practice_app/main_app/post/templates/post/category_form.html
  practice_app/main_app/post/templates/post/category_form_two.html
  practice_app/main_app/post/templates/post/category_posts.html
  practice_app/main_app/post/templates/post/corona_data.html
  practice_app/main_app/post/templates/post/country_form.html
  practice_app/main_app/post/templates/post/home.html
  practice_app/main_app/post/urls.py
  practice_app/main_app/post/views.py
  practice_app/main_app/users/migrations/0002_userprofile.py
  practice_app/main_app/users/migrations/__pycache__/0001_initial.cpython-310.pyc
  practice_app/main_app/users/migrations/__pycache__/0002_userprofile.cpython-310.pyc
  practice_app/main_app/users/migrations/__pycache__/__init__.cpython-310.pyc
Labels: Status: Review Needed

#191 Category functionality is implemented
  practice_app/main_app/dnsApi/__pycache__/__init__.cpython-310.pyc
  practice_app/main_app/dnsApi/__pycache__/admin.cpython-310.pyc
  practice_app/main_app/dnsApi/__pycache__/apps.cpython-310.pyc
  practice_app/main_app/dnsApi/__pycache__/forms.cpython-310.pyc
  practice_app/main_app/dnsApi/__pycache__/models.cpython-310.pyc
  practice_app/main_app/dnsApi/__pycache__/urls.cpython-310.pyc
  practice_app/main_app/dnsApi/__pycache__/views.cpython-310.pyc
  practice_app/main_app/dnsApi/migrations/__pycache__/__init__.cpython-310.pyc
  practice_app/main_app/main_app/settings.py
  practice_app/main_app/post/admin.py
  practice_app/main_app/post/migrations/0006_post_category.py
  practice_app/main_app/post/migrations/0007_category.py
  practice_app/main_app/post/migrations/0008_alter_category_post.py
  practice_app/main_app/post/migrations/__pycache__/0001_initial.cpython-310.pyc
  practice_app/main_app/post/migrations/__pycache__/0002_post_location.cpython-310.pyc
  practice_app/main_app/post/migrations/__pycache__/0003_post_likes.cpython-310.pyc
  practice_app/main_app/post/migrations/__pycache__/0004_post_dislikes.cpython-310.pyc
  practice_app/main_app/post/migrations/__pycache__/0005_comment.cpython-310.pyc
  practice_app/main_app/post/migrations/__pycache__/0006_post_category.cpython-310.pyc
  practice_app/main_app/post/migrations/__pycache__/0007_category.cpython-310.pyc
  practice_app/main_app/post/migrations/__pycache__/0008_alter_category_post.cpython-310.pyc
  practice_app/main_app/post/migrations/__pycache__/__init__.cpython-310.pyc
  practice_app/main_app/post/models.py
  practice_app/main_app/post/templates/post/base.html
  practice_app/main_app/post/templates/post/category_posts.html
  practice_app/main_app/post/templates/post/home.html
  practice_app/main_app/post/urls.py
  practice_app/main_app/post/views.py
  practice_app/main_app/users/migrations/0002_userprofile.py
  practice_app/main_app/users/migrations/__pycache__/0001_initial.cpython-310.pyc
  practice_app/main_app/users/migrations/__pycache__/0002_userprofile.cpython-310.pyc
  practice_app/main_app/users/migrations/__pycache__/__init__.cpython-310.pyc
Labels: Status: Review Needed

#194 Profile get and post apis
  practice_app/main_app/post/templates/post/base.html
  practice_app/main_app/post/templates/post/home.html
  practice_app/main_app/post/templates/post/post_detail.html
  practice_app/main_app/post/urls.py
  practice_app/main_app/users/urls.py
  practice_app/main_app/users/views.py
Labels: Status: Review Needed

#195 Profile get and post apis
  practice_app/main_app/post/urls.py
  practice_app/main_app/users/urls.py
  practice_app/main_app/users/views.py
Labels: Status: Review Needed

#203 Feature/api posts
  practice_app/main_app/main_app/urls.py
  practice_app/main_app/post/serializers.py
  practice_app/main_app/post/templates/post/base.html
  practice_app/main_app/post/templates/post/life_expectancy.html
  practice_app/main_app/post/urls.py
  practice_app/main_app/post/views.py
  practice_app/main_app/users/urls.py
Labels: Category - Enhancement, Priority - High, Status: Review Needed

#208 Tests/unittesting for posts
  practice_app/main_app/post/tests.py
  practice_app/main_app/post/views.py
Labels: Status: Review Needed, Priority: Severe

#216 Unit tests implemented for profile
  practice_app/main_app/main_app/settings.py
  practice_app/main_app/post/admin.py
  practice_app/main_app/users/tests/test_views.py
  practice_app/main_app/users/urls.py
Labels: Status: Review Needed, Priority: Severe

#219 Tests/unittesting post
  practice_app/main_app/dnsApi/__pycache__/tests.cpython-38.pyc
  practice_app/main_app/main_app/urls.py
  practice_app/main_app/post/migrations/0009_country_remove_category_post_alter_category_name_and_more.py
  practice_app/main_app/post/migrations/__pycache__/0005_comment.cpython-38.pyc
  practice_app/main_app/post/migrations/__pycache__/0006_post_category.cpython-38.pyc
  practice_app/main_app/post/migrations/__pycache__/0007_category.cpython-38.pyc
  practice_app/main_app/post/migrations/__pycache__/0008_alter_category_post.cpython-38.pyc
  practice_app/main_app/post/migrations/__pycache__/0009_country_remove_category_post_alter_category_name_and_more.cpython-38.pyc
  practice_app/main_app/post/serializers.py
  practice_app/main_app/post/templates/post/base.html
  practice_app/main_app/post/templates/post/life_expectancy.html
  practice_app/main_app/post/templates/post/new_face.html
  practice_app/main_app/post/tests.py
  practice_app/main_app/post/urls.py
  practice_app/main_app/post/views.py
  practice_app/main_app/users/migrations/__pycache__/0001_initial.cpython-38.pyc
  practice_app/main_app/users/migrations/__pycache__/0002_userprofile.cpython-38.pyc
  practice_app/main_app/users/tests/__pycache__/__init__.cpython-38.pyc
  practice_app/main_app/users/tests/__pycache__/test_models.cpython-38.pyc
  practice_app/main_app/users/tests/__pycache__/test_urls.cpython-38.pyc
  practice_app/main_app/users/tests/__pycache__/test_views.cpython-38.pyc
  practice_app/main_app/users/urls.py
  practice_app/main_app/users/views.py
Labels: Status: Review Needed
