Repository bounswe/bounswe2022group4, pull requests merged in 2022-10, with the labels that each got.

#265 Implementing login page using e-mail and password without backend connection
  heka-front/package-lock.json
  heka-front/package.json
  heka-front/src/pages/SignInPage/SignInPage.css
  heka-front/src/pages/SignInPage/SignInPage.js
Labels: Status: Completed, Frontend

#261 Backend: Swagger integrated to get self-generated API documentation
  README.md
  backend/heka/heka/settings.py
  backend/heka/heka/urls.py
  backend/heka/requirements.txt
  backend/heka/templates/swagger-ui.html
  backend/heka/users/views.py
Labels: Priority - Medium, Status: Review Needed, Team - Backend

#273 implement auth logic with register and login fragments
  heka-mobile/.idea/deploymentTargetDropDown.xml
  heka-mobile/.idea/misc.xml
  heka-mobile/app/src/main/AndroidManifest.xml
  heka-mobile/app/src/main/java/com/bounswe/heka/MainActivity.kt
  heka-mobile/app/src/main/java/com/bounswe/heka/data/HomeResponse.kt
  heka-mobile/app/src/main/java/com/bounswe/heka/data/LoginRequest.kt
  heka-mobile/app/src/main/java/com/bounswe/heka/data/LoginResponse.kt
  heka-mobile/app/src/main/java/com/bounswe/heka/data/LogoutResponse.kt
  heka-mobile/app/src/main/java/com/bounswe/heka/data/RegisterRequest.kt
  heka-mobile/app/src/main/java/com/bounswe/heka/data/RegisterResponse.kt
  heka-mobile/app/src/main/java/com/bounswe/heka/login/LoginFragment.kt
  heka-mobile/app/src/main/java/com/bounswe/heka/login/LoginViewModel.kt
  heka-mobile/app/src/main/java/com/bounswe/heka/network/ApiService.kt
  heka-mobile/app/src/main/java/com/bounswe/heka/profile/ProfileFragment.kt
  heka-mobile/app/src/main/java/com/bounswe/heka/profile/ProfileViewModel.kt
  heka-mobile/app/src/main/java/com/bounswe/heka/register/RegisterFragment.kt
  heka-mobile/app/src/main/java/com/bounswe/heka/register/RegisterViewModel.kt
  heka-mobile/app/src/main/java/com/bounswe/heka/utils/EmailValidator.kt
  heka-mobile/app/src/main/java/com/bounswe/heka/utils/PasswordValidator.kt
  heka-mobile/app/src/main/java/com/bounswe/heka/utils/UsernameValidator.kt
  heka-mobile/app/src/main/res/layout/fragment_login.xml
  heka-mobile/app/src/main/res/layout/fragment_profile.xml
  heka-mobile/app/src/main/res/layout/fragment_register.xml
  heka-mobile/app/src/main/res/menu/menu_main.xml
  heka-mobile/app/src/main/res/navigation/nav_graph.xml
  heka-mobile/app/src/main/res/values/strings.xml
  heka-mobile/app/src/main/res/xml/network_security_config.xml
Labels: Team - Mobile

#274 Login page is connected to backend now
  heka-front/src/pages/SignInPage/SignInPage.css
  heka-front/src/pages/SignInPage/SignInPage.js
  package-lock.json
Labels: Status: Completed, Frontend

#276 Heka front login UI improvement
  heka-front/src/pages/SignInPage/SignInPage.css
  heka-front/src/pages/SignInPage/SignInPage.js
Labels: Category - To Do, Priority - High, Status: Completed, whom: individual, Difficulty - Medium, Language - React.js, Team - Frontend

#281 Sign-Up was added
  heka-front/src/components/PostBox/PostBox.js
  heka-front/src/pages/SignUpPage/SignUpPage.js
Labels: Frontend

#283 Backend: Migrates from rest-framework-swagger to drf-yasg
  .gitignore
  backend/heka/heka/settings.py
  backend/heka/heka/urls.py
  backend/heka/requirements.txt
  backend/heka/users/views.py
Labels: Priority - Medium, Status: Review Needed, Team - Backend

#289 feat: UI improvements in homepage
  heka-front/src/components/PostBox/PostBox.js
  heka-front/src/pages/HomePage/HomePage.css
  heka-front/src/pages/HomePage/HomePage.js
Labels: Category - To Do, Priority - High, Status: Completed, whom: individual, Difficulty - Medium, Language - React.js, Team - Frontend

#290 feat: HomePage test cases
  heka-front/src/components/Post/Post.js
  heka-front/src/components/PostBox/PostBox.js
  heka-front/src/tests/HomePage.test.js
Labels: Category - To Do, Priority - High, Status: Completed, Difficulty - Medium, Language - React.js, Team - Frontend

#298 Backend: Implement unit tests for register and login functionalities.
  backend/heka/users/tests.py
  backend/heka/users/urls.py
  backend/heka/users/views.py
Labels: Priority - Medium, Status: Review Needed, Language - Python, Team - Backend

#301 Store Login Info in Global State and Using In Navigation Bar
  heka-front/src/App.js
  heka-front/src/components/Navbar/Navbar.js
  heka-front/src/pages/SignInPage/SignInPage.js
Labels: Category - To Do, Priority - High, whom: individual, Difficulty - Hard, Language - React.js, Team - Frontend

#305 Frontend - Profile page is added
  heka-front/src/pages/ProfilePage/ProfilePage.js
  heka-front/src/pages/ProfilePage/profilePage.css
Labels: Team - Frontend
